numberOfComments and Post fields
Septillion24/itsc-3155-final-project pull request #11
Opened 2024-04-24 20:41 UTC by James83701

2024-04-24 23:04 UTC, Septillion24 requested changes

2024-04-24 23:04 UTC, Septillion24 commented on classes/DataBaseHandler.py
> +    def numberOfComments(self, postID: int) -> int:
should be an attribute on post

2024-04-25 01:31 UTC, James83701 commented
changes made

2024-04-25 01:32 UTC, Septillion24 approved these changes
poggers

2024-04-25 01:35 UTC, merged